name Pipeline

on
  push
    branches [ main ]

jobs
  build-and-test
    runs-on ubuntu-latest
    steps
      - name Checkout repository code into runner
        uses actionscheckout@v2
      - name Set up JDK 11
        uses actionssetup-java@v2
        with
          java-version '11'
          distribution 'adopt'
      - name Test with Maven
        run mvn test -B